### ISSUE TITLE
请问您是如何实现在多边形内绘制线段

### ISSUE THREAD

**Issue by haoliyou93** [Char-Ten/cpRPA#1]
看了您的文章，现在还有个疑问就是如何实现在多边形内绘制线段并得到各个线段与多边形边框的交点。

**Comment by Char-Ten** [comment]
我说是手算你信吗23333。
好了不开玩笑，首先你能够拿到多边形的各个点吧，然后你也可以确定每条线段之间的间隔吧，那么接下来的事情就简单了，把间隔当成已知的y值，然后利用一次函数的两点表达式求x值，然后就可以获得交点了。
如果你需要斜线段的话，那么先将多边形旋转，然后继续上面的步骤，算好之后，把点再转回来
我觉得我的文章已经是写了够详细了啊。。。
[http://www.jianshu.com/p/015dd5b53263](http://www.jianshu.com/p/015dd5b53263)
斜线的原理如下图所示：
![GIF.gif](http://upload-images.jianshu.io/upload_images/2812131-e73f3f7b4c9862d5.gif?imageMogr2/auto-orient/strip)
