### ISSUE TITLE
你好，请问您有做过中间有障碍物的吗？

### ISSUE THREAD

**Issue by wsliliang** [Char-Ten/cpRPA#3]

**Comment by Char-Ten** [comment]
没有，不考虑避障。也不适用凹多边形规划地块。
避障需求，要么提高飞行高度，要么切割地块成凸边形。
我这个库只针对平面，导出来的数据都是经纬度，没有高度这个参数

**Comment by wsliliang** [comment]
我看到有些无人机是采用绕过的方式避障的，还是蛇形，只是绕过障碍物，继续沿之前的路线飞行

**Comment by Char-Ten** [comment]
绕过避障依赖的是无人机本身的避障飞行功能吧

**Comment by wsliliang** [comment]
不是，就是航线规划，就是求得航线与障碍物的交点，飞到交点时绕过，飞到另外一个交点，接着向前飞

**Comment by Char-Ten** [comment]
这个太复杂，不考虑

**Comment by wsliliang** [comment]
谢谢！
