### ISSUE TITLE
transform 函数

### ISSUE THREAD

**Issue by lber10** [Char-Ten/cpRPA#4]
你好, 麻烦能解释下transform那几个入参以及该方法的具体用途吗, 我这边准备做移动端用的, 谢谢;

**Comment by Char-Ten** [comment]
```javascript
/**
 * @desc 
 * ---
 * 点(x,y)绕点(tx,ty)旋转deg度后，x方向放大缩小sx倍，y方向放大缩小sy倍
 * ---
 * @param {Number} x - x
 * @param {Number} y - y
 * @param {Number} tx - 旋转中心tx
 * @param {Number} ty - 旋转中心ty
 * @param {Number} deg - 旋转角度deg
 * @param {Number} sx- x倍数sx，默认为1也就是不缩放
 * @param {Number} sy- y倍数sy，默认为1也就是不缩放
*/
function transform(x, y, tx, ty, deg, sx, sy) {
    var deg = deg * Math.PI / 180;
    if (!sy) sy = 1;
    if (!sx) sx = 1;
    return [
        sx * ((x - tx) * Math.cos(deg) - (y - ty) * Math.sin(deg)) + tx,
        sy * ((x - tx) * Math.sin(deg) + (y - ty) * Math.cos(deg)) + ty
      ]
}
```
---
具体可以参考一下我简书上的博客：[无人机航线规划思路剖析，基于凸多边形地块往复式运动](https://www.jianshu.com/p/015dd5b53263)

**Comment by lber10** [comment]
回复效率好高, 谢谢大佬! 博客我看了,有些原理不太清楚;     1. transform前两个参数, 这个x,y是矩形的哪个点?   2. 进行缩放的目的是什么?

**Comment by Char-Ten** [comment]
x,y是任意点，tx和ty也是任意点。  
在博客里面那个思路里面，是先用这个函数把任意凸多边形顶点旋转，然后取与维度线的交点，记录下这些点之后，再把凸多边形顶点与交点用这个函数旋转回来，从而实现不同角度航线的目的。  
之所以要转凸多边形的顶点，是因为平行于x轴的线都可以表示为`y=1 y=2 ... y=n`的形式，拿这些线去算交点，可以少算一个x变量，让计算变简单。  
缩放只是提供了这个功能，没有别的目的，可以不传。

**Comment by lber10** [comment]
得麻烦大佬一下, 实在抱歉~   计算交点坐标那一块卡了一天了,有点问题想请教, 可否加下QQ? 图文并茂的话,好描述一些, 谢谢了;  1710982906

**Comment by Char-Ten** [comment]
抱歉，有什么问题issue里面提就可以了，issue也可以传图的。  
我认为你照着我那篇博文的步骤一步步试着写下去是可以写出来的。  
先不要急着写任意角度的，  
就考虑最简单旋转度数为0的，  
即与x轴平行的线`y=1`，  
与任意一条直线`y=kx+b`求交点坐标应该会吧，  
初中的知识而已，  
结果很直接，  
交点就是`((1-b)/k,1)`，  

---
但是你要知道，  
在凸多边形里面，  
两个顶点决定一条边，也就是线段， 
你可以通过一次函数的两点式：  
![](http://upload-images.jianshu.io/upload_images/2812131-e6ecb86ec8e75c8b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)  
把两个顶点`(x1,y1) (x2,y2)`代进去可以得到这条边的一次函数表达式`y=kx+b`

---
当然
如果y=1的值介于y1~y2之间
那么y=1这条线必定与两个顶点`(x1,y1) (x2,y2)`连成的线段有交点！
所以在计算相交之前先判断一下
横线y=n是否介于两个顶点的y值之间
不是的话就不用继续计算了，都没有交点，计算了也没用

---

**Comment by lber10** [comment]
十分感谢, 当时项目比较赶,也是没有仔细阅读你的源码, 不过对我帮助很大, 谢谢!

在 2018-08-12 20:20:29，"CharTen" <notifications@github.com> 写道：


抱歉，有什么问题issue里面提就可以了，issue也可以传图的。
我认为你照着我那篇博文的步骤一步步试着写下去是可以写出来的。
先不要急着写任意角度的，
就考虑最简单旋转度数为0的，
即与x轴平行的线y=1，
与任意一条直线y=kx+b求交点坐标应该会吧，
初中的知识而已，
结果很直接，
交点就是((1-b)/k,1)，

但是你要知道，
在凸多边形里面，
两个顶点决定一条边，也就是线段，
你可以通过一次函数的两点式：

把两个顶点(x1,y1) (x2,y2)代进去可以得到这条边的一次函数表达式y=kx+b

当然
如果y=1的值介于y1~y2之间
那么y=1这条线必定与两个顶点(x1,y1) (x2,y2)连成的线段有交点！
所以在计算相交之前先判断一下
横线y=n是否介于两个顶点的y值之间
不是的话就不用继续计算了，都没有交点，计算了也没用
